# Generated by Django 3.0.2 on 2020-01-28 14:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
